### ISSUE TITLE
Can't get it to work for DRM stuff

### ISSUE THREAD

**Issue by crazyhorse77** [glennguy/plugin.video.9now#3]
Hi I have inputstream.adaptive enabled in Kodi 17.1 Win10.

I was never prompted to do anything about Widevine.
In the settings for inputstream.adaptive do i need to set anything, ie the decrypter path?

I try and play something and it doesn't work. I get the following:

22:16:34.637 T:13452   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: (3, 'The system cannot find the path specified', 'C:\\Users\\Anthony\\AppData\\Roaming\\Kodi\\cdm/*.*')
                                            Traceback (most recent call last):
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.9now\default.py", line 88, in <module>
                                                router(sys.argv[2][1:])
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.9now\default.py", line 81, in router
                                                play.play_video(params)
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.9now\resources\lib\play.py", line 44, in play_video
                                                if wvhelper.check_inputstream():
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.9now\resources\lib\wvhelper.py", line 76, in check_inputstream
                                                if not is_widevinecdm():
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.9now\resources\lib\wvhelper.py", line 104, in is_widevinecdm
                                                for file in os.listdir(cdm_path):
                                            WindowsError: (3, 'The system cannot find the path specified', 'C:\\Users\\Anthony\\AppData\\Roaming\\Kodi\\cdm/*.*')
                                            -->End of Python script error report<--
22:16:34.680 T:17668   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.9now/?action=listepisodes&episode_no=5&thumb=https%3A%2F%2Fimageresizer.static9.net.au%2F2BwCWAXwF8RXRtmHy5QLThNKq_0%3D%2F480x0%2Fhttps%253A%252F%252Fs3-ap-southeast-2.amazonaws.com%252Fvms-tv-images-prod%252F2017%252F03%252F60856%252FCEAP08_9_B_SchwarzeneggerTheCelebrityApprentice_S08E09.jpg&airdate=2017-03-14T13:00:00.000Z&fanart=https%3A%2F%2Fimageresizer.static9.net.au%2FXJCCA9r_3oPS0z8cOh1lDc2Omns%3D%2F1920x0%2Fhttps%253A%252F%252Fs3-ap-southeast-2.amazonaws.com%252Fvms-tv-images-prod%252F2017%252F02%252F55981%252FCEAP08_SchwarzeneggersCelebrityApprentice_1920.jpg&title=Ep 5 - I'm Going to Full Ballmer/I'm Going To Pump You Up&episode_name=I'm Going to Full Ballmer/I'm Going To Pump You Up&url=None&license_url=None&drm_id=cj06torsb00a90hmpzjnr3x5h&duration=4843&license_key=None&id=5356806837001&desc=Los Angeles Clippers -The teams have to create a high-energy presentation to promote the Clipper brand and fire up Clipper Nation during a timeout, as well as designing a T-shirt for fans.]

**Comment by glennguy** [comment]
Hi,

Try the latest zip. You're just missing the cdm folder and the script was
failing there. Should be all good now.

Fixed in ab9da15
<https://github.com/glennguy/plugin.video.9now/commit/ab9da159792769221a489d0b13d4a3428c27cc8b>

**Comment by crazyhorse77** [comment]
Thanks for your help. I now get further. It prompted me to install the two extra modules.

Now this error is what I get:
20:49:53.928 T:6832  NOTICE: VideoPlayer: Opening: http://9now-vod-dash-bc-origin.akamaized.net/4460760524001/4460760524001_5356824940001_5356806837001.mpd
20:49:53.928 T:6832 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
20:49:54.157 T:8676  NOTICE: Creating InputStream
20:49:54.343 T:8676   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://9now-vod-dash-bc-origin.akamaized.net/4460760524001/4460760524001_5356824940001_5356806837001.mpd)
20:49:54.345 T:8676   ERROR: CVideoPlayer::OpenInputStream - error opening [http://9now-vod-dash-bc-origin.akamaized.net/4460760524001/4460760524001_5356824940001_5356806837001.mpd]
20:49:54.345 T:8676  NOTICE: CVideoPlayer::OnExit()
20:49:54.345 T:6832   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.9now/?action=listepisodes&episode_no=5&thumb=https%3A%2F%2Fimageresizer.static9.net.au%2F2BwCWAXwF8RXRtmHy5QLThNKq_0%3D%2F480x0%2Fhttps%253A%252F%252Fs3-ap-southeast-2.amazonaws.com%252Fvms-tv-images-prod%252F2017%252F03%252F60856%252FCEAP08_9_B_SchwarzeneggerTheCelebrityApprentice_S08E09.jpg&airdate=2017-03-14T13:00:00.000Z&fanart=https%3A%2F%2Fimageresizer.static9.net.au%2FXJCCA9r_3oPS0z8cOh1lDc2Omns%3D%2F1920x0%2Fhttps%253A%252F%252Fs3-ap-southeast-2.amazonaws.com%252Fvms-tv-images-prod%252F2017%252F02%252F55981%252FCEAP08_SchwarzeneggersCelebrityApprentice_1920.jpg&title=Ep 5 - I'm Going to Full Ballmer/I'm Going To Pump You Up&episode_name=I'm Going to Full Ballmer/I'm Going To Pump You Up&url=None&license_url=None&drm_id=cj06torsb00a90hmpzjnr3x5h&duration=4843&license_key=None&id=5356806837001&desc=Los Angeles Clippers -The teams have to create a high-energy presentation to promote the Clipper brand and fire up Clipper Nation during a timeout, as well as designing a T-shirt for fans.]
20:49:54.382 T:6832  NOTICE: CVideoPlayer::CloseFile()
20:49:54.382 T:6832  NOTICE: VideoPlayer: waiting for threads to exit
20:49:54.383 T:6832  NOTICE: VideoPlayer: finished waiting
20:49:54.383 T:6832  NOTICE: CVideoPlayer::CloseFile()
20:49:54.383 T:6832  NOTICE: VideoPlayer: waiting for threads to exit
20:49:54.383 T:6832  NOTICE: VideoPlayer: finished waiting

**Comment by glennguy** [comment]
I'm finding the same on my end.

I think I might need to compile new decrypters. Leave it with me for a day or two, should be able to get it sorted.

**Comment by glennguy** [comment]
Ok, I've updated the Windows builds of ssd_wv.dll. Can you delete 'C:\Users\Anthony\AppData\Roaming\Kodi\cdm\ssd_wv.dll' and try playing again? Re-download the missing ssd_wv.dll

**Comment by crazyhorse77** [comment]
Yep, that fixes it. Thanks so much.

**Comment by glennguy** [comment]
Happy to help, and thanks for bringing it to my attention.
